name: Unit Tests
on: [push, pull_request]
jobs:
  go_tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        go:
          - '1.16'
          - '1.20'
    name: Go Tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go test ./...
